#!/usr/bin/env bash

if [ ! $(command -v singularity) ]; then
        module load singularity/3.8.4 squashfs/4.4
fi

PROGRAM=/home/biop/venv/bin/python
IMAGE=/cluster/tufts/levinlab/jstras02/confluentfucci_biop.sif
ENTRYPOINT_ARGS=""

## Determine Nvidia GPUs (to pass coresponding flag to Singularity)
if [[ $(nvidia-smi -L 2>/dev/null) ]]
then
        echo "BIOC: Enabling Nvidia GPU support in the container."
        OPTIONS="--nv"
fi
	
singularity exec $OPTIONS $IMAGE $ENTRYPOINT_ARGS $PROGRAM "$@"

